name: Go Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.5-dind
        options: --privileged
        ports:
        - 2375:2375

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: Enable Docker
      run: |
        sudo systemctl start docker
        docker info

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test -v -count=1 ./...
